//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioFundacionOscarez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactenos
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string email { get; set; }
        public string Telefono { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public bool AvisoPrivacidad { get; set; }
    }
}
