//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioFundacionOscarez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFundacionEntities : DbContext
    {
        public DbFundacionEntities()
            : base("name=DbFundacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contactenos> Contactenos { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<CaracteristicasxProyecto> CaracteristicasxProyecto { get; set; }
        public virtual DbSet<Proyectos> Proyectos { get; set; }
        public virtual DbSet<ResultadosxProyecto> ResultadosxProyecto { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
    }
}
